[project]
name = "text-chat"
version = "0.1.0"
description = "Minimal LLM chat interface for OpenAI"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[project.optional-dependencies]
test = [
  "pytest>=7.0.0"
]

[tool.uv]
package = true

[tool.pytest.ini_options]
testpaths = ["src"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
